name: npm-check-updates

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: npm-check-updates
      uses: actions/setup-node@v2
      with:
        node-version: lts/*
    - run: npx npm-check-updates -u
    
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: npm-check-updates
        file_pattern: package.json
